version: '3'

services:
  # C
  c-app:
    container_name: c
    build:
      context: ./docker/c_lessons
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./docker/c_lessons:/home/c_lessons
    ports:
      - "8080:80"
#    network_mode: "sample-network5"

#networks:
#  sample-network5: